articles/urls.py
from django.urls import path
from . import views

app_name="articles"

urlpatterns = [
    path('', views.articles_list,name="list"),
    path('<slug>',views.articles_detail,name="detail")
]
# domin.ir/articles/

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', views.home),
    path('articles/', include("articles.urls"))
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

class Articles(models.Model):
    title=models.CharField(max_length= 100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        this function shows registered title in list of articles, it can be body, or every data that we have inserted in admin page
        :return:
        """
        return self.title

    def snippet(self):
        """when a text is too long we can show only a certain character of it """
        return self.body[:50]+"..."

articles/views.py
from django.shortcuts import render,HttpResponse
from . import models


def articles_list(request):
    articles= models.Articles.objects.all().order_by("date")
    args={"articles":articles}
    return render(request,"articles/articleslist.html",args)

def articles_detail(request, slug):
    return HttpResponse(slug)

djangoblog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    # return HttpResponse("Hi! this is my about page")
    return render(request,"about.html")

def home(request):
    # return  HttpResponse("Hi! this is my homepage")
    return render(request,"home.html")

articles/templates/articles/articleslist.html
{%extends "base.html"%}
{%block title%}
articles
{%endblock%}
articles
{%block content%}
<div class="container">
    <h1>Article list</h1>
    {% for article in articles%}
    <h2>
        <a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a>
    </h2>
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    {% endfor %}
</div>
{%endblock%}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about</title>
</head>
<body>
<h1>About</h1>
<p>This is website about page</p>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8">
        <title>
        {%block title%}

        {%endblock%}
        </title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
    <h2><a href="{% url 'articles:list' %}">LOGO</a> </h2>
    <div class="wrapper">
        {% block content %}

        {%endblock%}
    </div>

    </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<h1>Home</h1>
<p>welcome to my Blog</p>
</body>
</html>